version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongodb
    env_file:
      - '.env'
  mongodb:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db-data:/db
