version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/db
